### ISSUE TITLE
Is this deployed in hush-house?

### ISSUE THREAD

**Issue by aegershman** [cirocosta/flight_recorder#4]
Hey there!

Apologies, don't mean to be a creep, just trying to understand how the `hush-house` metrics deployments are setup. I have prometheus/grafana deployed on a helm-based Concourse deployment && it's based entirely on the `hush-house` metrics deployment. However, the `flight_recorder` grafana dashboard does not return data. I'm now under the impression that dashboard is dependent on this Prometheus exporter(?).

Is that the case? If so, will this project ever move into the hush-house deployment? Or include more official deployment instructions.

Not trying to pester or put you on the spot, just curious.

Thanks!

**Comment by cirocosta** [comment]
Hey @aegershman ,

That's a good point - it is deployed there! It uses the same chart as in [flight_recorder/helm/flight-recorder](https://github.com/cirocosta/flight_recorder/tree/master/helm/flight-recorder). It's currently under "let's experiment and see if there are more data that we want to gather / things to improve".

> I'm now under the impression that dashboard is dependent on this Prometheus exporter(?).
> will this project ever move into the hush-house deployment? 

yepp and yepp!

I'm planning to do some cleaning there in the `concourse/hush-house` repo very soon, so adding `flight_recorder` there is something that would be landing there under `deployments/with-creds` (as it requires your database credentials) 😁

What made me not move the chart there yet is just that I wanted to first see if there'd be a nice way of having the chart in this repo and somehow referencing it from there (without having to maintain an actual Charts repository).

---


(some heads up):

- similar to `Flight Recorder`, there's another dashboard (`SLIs`) that needs an extra exporter too: https://github.com/cirocosta/slirunner.

- in the `Concourse` dashboard you'll see that the `worker errors` panel requires integration with `stackdriver` - that's because we have a "log-based metric" configured there to capture the errors

- there's a `stackdriver` (pretty bad totally non-descriptive title 😅 ) dashboard that consumes some other log-based metrics from `stackdriver` - that's consuming the audit logs


---

I hope this helps!

Please let me know if there are things you'd like to have `flight_recorder` capturing that you'd find useful for you to keep track of your Concourse installation.

PRs are welcomed too 😁 

Thank you! (*and please, keep asking! those are great questions!*)

**Comment by aegershman** [comment]
Awesome, thanks a lot for your response 👍  I'm following your / hush-house expertise, but also apologies, don't mean to creep around / impose on all these repos.

Sidenote, if you _were_ to host this (and other charts) as it's own chart repo, you might get some value out of [helm/chart-releaser](https://github.com/helm/chart-releaser)? I haven't used it personally, but any custom charts at work I host using github-pages, and it appears chart-releaser handles most of the automation for that. Just sharing 👌 

Regardless, it's definitely valuable to have the charts accessible from the `helm` cli (e.g. as a custom helm repo), because then I can ~steal it~ use it in my clusters just like any other chart deployment w/o having to copy-paste a custom deployment into my workspace. Not trying to push one way or the other, just sharing experience.

Thanks! Feel free to close whenever.

**Comment by cirocosta** [comment]
oooh interesting, I hadn't looked at `chart-releases` before, thanks for sharing! I think I might end up using it 👀 

For https://github.com/concourse/charts/ (which is a fork of `helm/charts` where we put some PRs on top of it when needed - see https://hush-house.pivotal.io/teams/main/pipelines/concourse-charts) we have a Concourse pipeline that publishes a charts repository under `gh-pages` (see the `maintenance` branch), but I was quite lazy to have something similar set up for other repos 😅 I wonder if there's some opportunity here in terms of making this maybe a "shared task" (like https://github.com/concourse/builder-task), a sample pipeline or, who knows, a resource? 🤔 

---

> Feel free to close whenever.

cool, closing it then 😁  thxx!
